spring.datasource.url=jdbc:postgresql://localhost:5432/spring_data_jpa
spring.datasource.username=postgres
spring.datasource.password=summer@msg
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8081
logging.level.com.example.demo=DEBUG